name: flutter_weather
description: Weather application

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

# Networking
  dio: ^4.0.6

# Models
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1

# Styling
  lottie: ^1.4.2
  flutter_svg: ^1.1.4
  responsive_grid: ^2.1.0

# State Management
  flutter_bloc: ^8.1.1

# Misc
  intl: ^0.17.0

dev_dependencies:
  integration_test:
    sdk: flutter


  freezed: ^2.1.0+1
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0

# Testing
  mockito: ^5.3.0


flutter:

  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/svg/